repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks # Hinders git commit with too large files.
    rev: v4.6.0
    hooks:
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: check-json
    - id: check-yaml

- repo: https://github.com/astral-sh/ruff-pre-commit # Checks for pep257 compliance and formats code.
  rev: 'v0.6.3'
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: ['--fix']
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]